# Generated by Django 4.1.7 on 2023-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='blog_rasm')),
                ('mavzu', models.CharField(max_length=200)),
                ('malumot', models.TextField(blank=True, null=True)),
                ('vaqt', models.DateTimeField()),
                ('soni', models.FloatField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
            },
        ),
        migrations.CreateModel(
            name='Ishtirokchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='ishtirokchi_rasm')),
                ('ism_sharif', models.CharField(max_length=200)),
                ('tugilgan_yil', models.DateField(blank=True, null=True)),
                ('manzil', models.CharField(blank=True, max_length=200, null=True)),
                ('telefon', models.IntegerField()),
                ('telegram', models.CharField(max_length=1000)),
                ('instagram', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Ishtirokchi',
                'verbose_name_plural': 'Ishtirokchilar',
            },
        ),
        migrations.CreateModel(
            name='Jamoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotip', models.ImageField(upload_to='jamoa_rasm')),
                ('jamoa_nomi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='jamoa_rasm')),
                ('malumot', models.TextField()),
                ('shior', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('telefon', models.IntegerField()),
                ('muallif', models.CharField(max_length=200)),
                ('albom1', models.ImageField(blank=True, null=True, upload_to='jamoa_rasm')),
                ('albom2', models.ImageField(blank=True, null=True, upload_to='jamoa_rasm')),
                ('albom3', models.ImageField(blank=True, null=True, upload_to='jamoa_rasm')),
                ('albom4', models.ImageField(blank=True, null=True, upload_to='jamoa_rasm')),
            ],
            options={
                'verbose_name': 'Jamoa',
                'verbose_name_plural': 'Jamoa',
            },
        ),
        migrations.CreateModel(
            name='Mijoz_fikri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='blog_rasm')),
                ('ism_sharif', models.CharField(max_length=200)),
                ('izoh', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='portfolio_rasm')),
                ('nom', models.CharField(max_length=200)),
                ('izoh', models.TextField()),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfoliolar',
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('soni', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
            },
        ),
        migrations.CreateModel(
            name='Video_darslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('muallif', models.CharField(max_length=200)),
                ('link', models.URLField(help_text="youtu.be ning o'rniga youtube.com/embed so'zini kiriting")),
                ('sana', models.DateField(max_length=200)),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
            },
        ),
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='blog_rasm')),
                ('nomi', models.CharField(max_length=200)),
                ('malumot', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
    ]
